
'use strict';
const $ = id => document.getElementById(id);
const deck = ['fool','magician','priestess','emperor','sun','star','moon'];
const titles = ['The Fool','The Magician','The High Priestess','The Emperor','The Sun','The Star','The Moon'];
const cards = deck.map((name,i) => {
 const el=document.createElement('div');el.className='card';el.setAttribute('aria-label',titles[i]);
 const panels=Array.from({length:10},(_,j)=>{const panel=document.createElement('div');panel.className='paper-panel';panel.innerHTML='<div class="paper-face"><div class="paper-print" style="left:'+(-j*16)+'px;background-image:url(assets/'+name+'.webp)"></div></div><div class="paper-face paper-back"><div class="back-print" style="left:'+(-j*16)+'px"></div></div>';el.appendChild(panel);return panel;});
 $('stage').appendChild(el);return {el,i,panels,launched:false};
});
function paperPose(bend,bias){let x=0,z=0;return Array.from({length:10},(_,j)=>{const angle=bend*(Math.pow(j/9,bias)-.35),rad=angle*Math.PI/180;const pose={transform:'translate3d('+x+'px,0,'+z+'px) rotateY('+angle+'deg)'};x+=16*Math.cos(rad);z-=16*Math.sin(rad);return pose;});}
function bendPaper(c,v,duration){const amount=(Math.random()<.5?-1:1)*(82+Math.random()*26+v*24),bias=.75+Math.random()*1.25;const stages=[[0,0],[.12,.18],[.28,1],[.48,1],[.66,.34],[.82,-.14],[1,0]];const poses=stages.map(([offset,strength])=>paperPose(reduced?0:amount*strength,bias));c.panels.forEach((panel,j)=>panel.animate(stages.map(([offset],k)=>({...poses[k][j],offset})),{duration,easing:'ease-in-out',fill:'forwards'}));}

let stream=null,ctx=null,analyser=null,data=null,frame=0,session=0,running=false,flight=0,restore=0,last=0,energy=0,noise=.006,calUntil=0,samples=[],smooth=0,previous=0,previewTimer=0;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function stack(){clearInterval(previewTimer);clearTimeout(restore);cards.forEach(c=>{c.el.getAnimations({subtree:true}).forEach(a=>a.cancel());c.panels.forEach((panel,j)=>{panel.style.transform='translate3d('+(j*16)+'px,0,0)';});c.launched=false;c.el.style.opacity='1';c.el.style.transform='translate3d('+(c.i-2)*4+'px,'+(4-c.i)*-3+'px,0) rotate('+((c.i-2)*4)+'deg)';});energy=0;flight=0;$('remaining').textContent=cards.length+' / '+cards.length;}
function wind(v){v=Math.max(0,Math.min(1,v));const n=Math.round(v*100);$('bar').style.width=n+'%';$('power').textContent=n+'%';$('meter').setAttribute('aria-valuenow',n);}
function launch(v){const c=[...cards].reverse().find(c=>!c.launched);if(!c)return;c.launched=true;flight++;$('remaining').textContent=(cards.length-flight)+' / '+cards.length;const duration=reduced?180:2600-v*200;bendPaper(c,v,duration);const start=c.el.style.transform;const dx=(c.i%2?1:-1)*(130+Math.random()*130)*(.7+v);const dy=-240-v*190;const turn=(c.i%2?1:-1)*(120+v*220);const sway=(c.i%2?1:-1)*(18+Math.random()*8);const anim=c.el.animate([{transform:start,opacity:1},{transform:start+' translateY(-10px) rotateX(-12deg) rotateY('+sway+'deg)',opacity:1,offset:.28},{transform:start+' translateY(-16px) rotateX(-18deg) rotateY('+sway+'deg)',opacity:1,offset:.48},{transform:'translate3d('+dx*.18+'px,-75px,70px) rotateX(50deg) rotateY('+sway+'deg) rotateZ('+turn*.15+'deg)',opacity:1,offset:.64},{transform:'translate3d('+dx+'px,'+dy+'px,150px) rotateX('+(200+v*300)+'deg) rotateY(120deg) rotateZ('+turn+'deg)',opacity:0}],{duration,easing:'cubic-bezier(.2,.65,.4,1)',fill:'forwards'});anim.onfinish=()=>{c.el.style.opacity='0';};if(flight===cards.length){$('status').textContent='漂亮！全場吹散。再來一次？';restore=setTimeout(()=>{stack();$('status').textContent='牌已回到桌上，再許一個願望。';},2800);}}
function stop(message){session++;running=false;cancelAnimationFrame(frame);clearInterval(previewTimer);if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;if(ctx)ctx.close().catch(()=>{});ctx=null;analyser=null;data=null;wind(0);$('mic').disabled=false;$('mic').textContent='開啟麥克風';if(message)$('status').textContent=message;}
function tick(now){if(!running||!analyser)return;const dt=Math.min(.05,(now-previous)/1000||.016);previous=now;analyser.getByteTimeDomainData(data);let sum=0;for(const b of data){const x=(b-128)/128;sum+=x*x;}const rms=Math.sqrt(sum/data.length);if(now<calUntil){samples.push(rms);wind(0);}else{if(samples.length){samples.sort((a,b)=>a-b);noise=Math.max(.003,samples[Math.floor(samples.length*.6)]);samples=[];$('status').textContent='準備好了，對著麥克風輕輕吹氣。';}const v=Math.min(1,Math.max(0,rms-noise*1.8-.008)*Number($('sensitivity').value)*7);smooth+=(v-smooth)*.3;wind(smooth);energy=smooth>.12?energy+smooth*dt:Math.max(0,energy-dt);if(energy>.055&&now-last>140){launch(smooth);last=now;energy=0;}}frame=requestAnimationFrame(tick);}
$('mic').addEventListener('click',async()=>{if(running){stop('麥克風已關閉。');return;}if(!window.isSecureContext||!navigator.mediaDevices?.getUserMedia){$('status').textContent='請透過 HTTPS 網址，用 Safari 或 Chrome 開啟。';return;}const token=++session;$('mic').disabled=true;$('status').textContent='請允許麥克風存取…';try{const Audio=window.AudioContext||window.webkitAudioContext;ctx=new Audio();await ctx.resume();const obtained=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false},video:false});if(token!==session){obtained.getTracks().forEach(t=>t.stop());return;}stream=obtained;analyser=ctx.createAnalyser();analyser.fftSize=1024;ctx.createMediaStreamSource(stream).connect(analyser);data=new Uint8Array(analyser.fftSize);running=true;samples=[];smooth=0;calUntil=performance.now()+1500;previous=performance.now();stack();$('mic').textContent='關閉麥克風';$('mic').disabled=false;$('status').textContent='校正環境音中，請安靜 1.5 秒…';stream.getAudioTracks()[0].onended=()=>{if(running)stop('麥克風連線已中斷，請重新開啟。');};frame=requestAnimationFrame(tick);}catch(e){if(token!==session)return;const msg=e.name==='NotAllowedError'?'麥克風未獲允許。請在瀏覽器網站設定允許後重試。':e.name==='NotFoundError'?'找不到麥克風，可先點「試吹一下」。':'無法啟動麥克風，請關閉其他錄音程式後重試。';stop(msg);}});
function simulate(){
 clearInterval(previewTimer); if(cards.every(c=>c.launched))stack();
 $('status').textContent='讓氣流，揭開命運的一角。';
 wind(.8);launch(.8);
 previewTimer=setTimeout(()=>wind(0),520);
}
$('test').addEventListener('click',simulate);
$('stage').addEventListener('click',simulate);
$('stage').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();simulate();}});
$('reset').addEventListener('click',()=>{stack();$('status').textContent=running?'牌已疊好，繼續吹氣吧。':'牌已疊好，可以再試一次。';});
document.addEventListener('visibilitychange',()=>{if(document.hidden)stop('已暫停麥克風，回來後請重新開啟。');});window.addEventListener('pagehide',()=>stop());stack();
